
apiVersion: apps/v1
kind: Deployment
metadata:
  name: devops-backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: devops-backend
  template:
    metadata:
      labels:
        app: devops-backend
    spec:
      containers:
        - name: backend
          image: ivykiera/nginx-web-page-backend:v1   # <--- Use your Docker Hub image
          ports:
            - containerPort: 3000
          env:
            - name: PGHOST
              value: postgres
            - name: PGUSER
              value: postgres
            - name: PGPASSWORD
              value: mysecretpassword
            - name: PGDATABASE
              value: devopsacademy
---
apiVersion: v1
kind: Service
metadata:
  name: devops-backend
spec:
  type: ClusterIP
  selector:
    app: devops-backend
  ports:
    - port: 3000
      targetPort: 3000
