version: '3.8'
services:
  db:
    image: postgres:16
    environment:
      - POSTGRES_PASSWORD=mysecretpassword
      - POSTGRES_DB=devopsacademy
    volumes:
      - pgdata:/var/lib/postgresql/data

  backend:
    build: ./backend
    image: ivykiera/nginx-web-page-backend:v1   # <--- Add this line for backend if you want to push it too!
    environment:
      - PGHOST=db
      - PGUSER=postgres
      - PGPASSWORD=mysecretpassword
      - PGDATABASE=devopsacademy
    depends_on:
      - db

  frontend:
    build: .
    image: ivykiera/nginx-web-page-frontend:v1  # <--- Add this line!
    ports:
      - "8080:80"
    depends_on:
      - backend

volumes:
  pgdata:

