apiVersion: apps/v1
kind: Deployment
metadata:
  name: devops-frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: devops-frontend
  template:
    metadata:
      labels:
        app: devops-frontend
    spec:
      containers:
        - name: frontend
          image: devops-academy-nginx:latest
          ports:
            - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: devops-frontend
spec:
  type: NodePort
  selector:
    app: devops-frontend
  ports:
    - port: 80
      targetPort: 80
      nodePort: 30080  # Expose on http://localhost:30080
